### ISSUE TITLE
Consultation on Trie Tree Maintenance？

### ISSUE THREAD

**Issue by ZipECHO** [alipay/PainlessInferenceAcceleration#15]
Hi, I have noticed that there are also two mode(input and output) in[ Tree class](https://github.com/alipay/PainlessInferenceAcceleration/blob/a5bc8b26b0e9d5e8aaedd31853f0527c4b47bd22/pia/lookahead/common/lookahead_cache.py#L34). Could you please explain why these two modes need to be set, and what operations they correspond to on the Trie tree?

**Comment by chenliangjyj** [comment]
We will release the nodes with the mode tag _input_ after the generation of the current query.  We assume that the benefit of the current query's prompt to the next query is less than the gradually increasing time cost it incurs.

**Comment by ZipECHO** [comment]
Thank you for your reply. Do you means that you add nodes of the current query prompt before inference in [add](https://github.com/alipay/PainlessInferenceAcceleration/blob/6280cb2f097ba0bc6bc423ab910b9de7ddbe3bf2/pia/lookahead/common/pretrained_model_batch.py#L1200)? Then you remove these node in [remove1](https://github.com/alipay/PainlessInferenceAcceleration/blob/6280cb2f097ba0bc6bc423ab910b9de7ddbe3bf2/pia/lookahead/common/pretrained_model_batch.py#L1254) or [remove2](https://github.com/alipay/PainlessInferenceAcceleration/blob/6280cb2f097ba0bc6bc423ab910b9de7ddbe3bf2/pia/lookahead/common/pretrained_model_batch.py#L1293) after the inference done. I am not sure which one corresponds to the release process. Beside, could you explain  the function of stream_put of lookahead_cache? Thanks!

**Comment by zheyishine** [comment]
Q1: Yes.
Q2: We remove the nodes of prompts [here](https://github.com/alipay/PainlessInferenceAcceleration/blob/6280cb2f097ba0bc6bc423ab910b9de7ddbe3bf2/pia/lookahead/common/lookahead_cache.py#L365C1-L366C1).  
Q3: `stream_put` is used for putting generated tokens into lookahead_cache as soon as possible rather than the final step(i.e., the `put` function). We use a buffer in `stream_put` to accumulate tokens to the length of `decoding_length` to avoid breaking a branch. `stream_put` is better than `put` when a response contains repeated token pieces.

**Comment by ZipECHO** [comment]
Thank you very much~, I am clearly understand this part now.

**Comment by ZipECHO** [comment]
Hi guys, I have another questions about Trie tree maintenance. 

1. Why there are two kind of trees [_update_trees](https://github.com/alipay/PainlessInferenceAcceleration/blob/a5bc8b26b0e9d5e8aaedd31853f0527c4b47bd22/pia/lookahead/common/lookahead_cache.py#L336) and [_update_input_trees](https://github.com/alipay/PainlessInferenceAcceleration/blob/a5bc8b26b0e9d5e8aaedd31853f0527c4b47bd22/pia/lookahead/common/lookahead_cache.py#L337)，and what are the funtions difference between them?  

2. I guess you add prompts into `_update_input_trees` and release it when finished an inference of a prompt. And the inference results will be add into `_update_trees` and this set will be squeezed and released after its length exceed 1024 in [here](https://github.com/alipay/PainlessInferenceAcceleration/blob/a5bc8b26b0e9d5e8aaedd31853f0527c4b47bd22/pia/lookahead/common/lookahead_cache.py#L567), do I understand correctly? 

3. Besides, will these release actions will affect (remove nodes or update freqs) the `mem`? or just affect `_update_trees` and `_update_input_trees`?

**Comment by ZipECHO** [comment]
Thanks~
