### ISSUE TITLE
这个lookahead的实现和原版hao-ailab的实现相比优化点在哪里？

### ISSUE THREAD

**Issue by janelu9** [alipay/PainlessInferenceAcceleration#4]

**Comment by zheyishine** [comment]
这两个算法刚好名字重复了，算法是不一样的，可以看对应的论文。开源前我们的lookahead已经在内部场景上线了大半年了，开源的时候就继续沿用内部名字了。

**Comment by janelu9** [comment]
> 这两个算法刚好名字重复了，算法是不一样的，可以看对应的论文。开源前我们的lookahead已经在内部场景上线了大半年了，开源的时候就继续沿用内部名字了。

我理解主要思路差不多，先猜测几个候选短序列，然后过一次decoder验证。这种方法可能对发散性生成不会太多损失精度。
