### ISSUE TITLE
BUG for chatglm3-6b and Qwen-14B-Int4

### ISSUE THREAD

**Issue by AGI-Jarvis** [alipay/PainlessInferenceAcceleration#7]
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/52863e13-e6a4-4687-b53c-547e31e1d0aa)
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/637c1625-bcdf-441a-b2f6-bf4657d8246a)
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/638747f5-67c1-44a0-8463-3fd9e20ea99d)

**Comment by chenliangjyj** [comment]
1. For chatglm3-6b , we just upload a test script. [https://github.com/alipay/PainlessInferenceAcceleration/blob/main/pia/lookahead/examples/chatglm3_example.py](url)
2. Please turn off the sample strategy when you test, the first two results without lookahead seems different. We only support greedy search for now.

**Comment by AGI-Jarvis** [comment]
> 1. For chatglm3-6b , we just upload a test script. [https://github.com/alipay/PainlessInferenceAcceleration/blob/main/pia/lookahead/examples/chatglm3_example.py](url)
> 2. Please turn off the sample strategy when you test, the first two results without lookahead seems different. We only support greedy search for now.

Qwen-14B-Int4已设置贪婪解码，lookahead=True时测试了四次输出，从图上的结果看来可能是因为重复惩罚还没支持造成的？lookahead=True时的token/s的数据看起来有点奇怪
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/b07769bb-b0eb-49ed-91de-d7bb0b721614)

chatglm3更新后已正常运行，但好像输出格式还有点小毛病，并且会有中英混杂输出和输出一半就停止的情况。从测试来看lookahead在首次运行的时候速度是会比较慢是吧？第二次开始才会有加速效果？不过项目加速效果确实很棒！期待Qwen支持重复惩罚后的效果！
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/68a3b8d6-05a8-466c-86cf-c2211c0ce207)

**Comment by AGI-Jarvis** [comment]
不过在检索增强生成的场景中，如果prompt发生微小的改变就又会回到慢的速度了，例如“编一个200字左右的儿童故事”和“写一个200字左右的儿童故事”

**Comment by AGI-Jarvis** [comment]
此外我还发现，chatglm3的重复惩罚设置的是1.0，官方设置的是1.1，是1.0会更适合我们的框架吗？

**Comment by chenliangjyj** [comment]
1.目前repetition_penalty还没有支持，建议设置为None
2.lookahead首次运行相当于在调整生成概率，所以加速比不高。对于prompt发生小改动的问题，在线使用场景，通常服务是挂起的，所以概率可以在内存中实时更新，如果生成跟之前query相似的回答应该是会快的。
3. chatglm那个max_new_token有设限吗
非常感谢试用我们的框架

**Comment by AGI-Jarvis** [comment]
![image](https://github.com/alipay/PainlessInferenceAcceleration/assets/155097476/b24ec120-3637-4e4e-8e75-c5350ab25f30)
1、我在qwen的example中看到了重复惩罚尚未支持，在glm3的example中看到默认设置的1.0
2、如图，差一个字都不行，或许可以考虑加个bert来改善这个问题？毕竟大部分检索增强的场景中每次的输出和输出还是差异很大的。此外如果一直挂起，问答多了之后内存会不会炸了呀？虽然我测试了几十条好像暂时没啥事
3、已解决，眼瞎了没注意，还以为是特性
